# Generated by Django 5.0.6 on 2024-06-16 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_furniturecategory_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_method', models.CharField(max_length=250)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.furniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay',
            },
        ),
    ]
