# Generated by Django 5.0.6 on 2024-06-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_orders_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
